logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

jwt:
  private-key:
  public-key:

spring:
  jpa:
    generate-ddl: true
  datasource:
    url:
    username:
    password:
  sendgrid:
    api-key:

finnhub:
  symbols:
  token:

verification:
  endpoint:
  template.id:
  email:
